apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  annotations:
    crossplane.io/composition-resource-name: route
    crossplane.io/external-create-pending: "2026-03-23T13:45:40Z"
    crossplane.io/external-create-succeeded: "2026-03-23T13:45:40Z"
    crossplane.io/external-name: r-rtb-06c67bc60754fb5831080289494
  creationTimestamp: "2026-03-23T13:41:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-29afa36010ce
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: d6663596-9361-464c-9f78-1ad462483669
  resourceVersion: "39390"
  uid: f4ed8d65-873b-49ad-9499-4ab3b4747812
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayId: igw-085d9e6f280c6bbee
    gatewayIdRef:
      name: configuration-aws-network-ab03c2a7f181
      namespace: default
    gatewayIdSelector:
      matchControllerRef: true
    region: us-west-2
    routeTableId: rtb-06c67bc60754fb583
    routeTableIdRef:
      name: configuration-aws-network-3bf4410e8d03
      namespace: default
    routeTableIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    carrierGatewayId: ""
    coreNetworkArn: ""
    destinationCidrBlock: 0.0.0.0/0
    destinationIpv6CidrBlock: ""
    destinationPrefixListId: ""
    egressOnlyGatewayId: ""
    gatewayId: igw-085d9e6f280c6bbee
    id: r-rtb-06c67bc60754fb5831080289494
    instanceId: ""
    instanceOwnerId: ""
    localGatewayId: ""
    natGatewayId: ""
    networkInterfaceId: ""
    origin: CreateRoute
    region: us-west-2
    routeTableId: rtb-06c67bc60754fb583
    state: active
    transitGatewayId: ""
    vpcEndpointId: ""
    vpcPeeringConnectionId: ""
  conditions:
  - lastTransitionTime: "2026-03-23T13:46:42Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2026-03-23T13:46:42Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-03-23T13:45:41Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
