apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: subnet-us-west-2a-192-168-128-0-18-private
    crossplane.io/external-create-pending: "2026-03-23T13:44:37Z"
    crossplane.io/external-create-succeeded: "2026-03-23T13:44:37Z"
    crossplane.io/external-name: subnet-09034369e27330cd6
  creationTimestamp: "2026-03-23T13:41:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 4
  labels:
    access: private
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
    zone: us-west-2a
  name: configuration-aws-network-5ce953f11bf5
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: d6663596-9361-464c-9f78-1ad462483669
  resourceVersion: "38893"
  uid: 6df0b3f4-db5e-4ca1-a121-eb017f5e31d6
spec:
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 192.168.128.0/18
    privateDnsHostnameTypeOnLaunch: ip-name
    region: us-west-2
    tags:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5ce953f11bf5
      crossplane-providerconfig: default
      kubernetes.io/role/internal-elb: "1"
    vpcId: vpc-0fc5d6edf6d0769f2
    vpcIdRef:
      name: configuration-aws-network-93e2e6ed5c73
      namespace: default
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:subnet/subnet-09034369e27330cd6
    assignIpv6AddressOnCreation: false
    availabilityZone: us-west-2a
    availabilityZoneId: usw2-az1
    cidrBlock: 192.168.128.0/18
    customerOwnedIpv4Pool: ""
    enableDns64: false
    enableLniAtDeviceIndex: 0
    enableResourceNameDnsARecordOnLaunch: false
    enableResourceNameDnsAaaaRecordOnLaunch: false
    id: subnet-09034369e27330cd6
    ipv6CidrBlock: ""
    ipv6CidrBlockAssociationId: ""
    ipv6Native: false
    mapCustomerOwnedIpOnLaunch: false
    mapPublicIpOnLaunch: false
    outpostArn: ""
    ownerId: "609897127049"
    privateDnsHostnameTypeOnLaunch: ip-name
    region: us-west-2
    tags:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5ce953f11bf5
      crossplane-providerconfig: default
      kubernetes.io/role/internal-elb: "1"
    tagsAll:
      crossplane-kind: subnet.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-5ce953f11bf5
      crossplane-providerconfig: default
      kubernetes.io/role/internal-elb: "1"
    vpcId: vpc-0fc5d6edf6d0769f2
  conditions:
  - lastTransitionTime: "2026-03-23T13:44:46Z"
    observedGeneration: 4
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2026-03-23T13:44:46Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-03-23T13:44:42Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
