apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/composition-resource-name: vpc
    crossplane.io/external-create-pending: "2026-03-23T13:43:39Z"
    crossplane.io/external-create-succeeded: "2026-03-23T13:43:39Z"
    crossplane.io/external-name: vpc-0fc5d6edf6d0769f2
    protection.fn.crossplane.io/block-deletion: "true"
    protection.fn.crossplane.io/reason: in use
    protection.fn.crossplane.io/replay-deletion: "true"
  creationTimestamp: "2026-03-23T13:41:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/composite: configuration-aws-network
    crossplane.io/in-use: "true"
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-93e2e6ed5c73
  namespace: default
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: configuration-aws-network
    uid: d6663596-9361-464c-9f78-1ad462483669
  resourceVersion: "40213"
  uid: ba40737f-e028-41c1-8e59-f07e04bc4c82
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-west-2
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-93e2e6ed5c73
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:609897127049:vpc/vpc-0fc5d6edf6d0769f2
    assignGeneratedIpv6CidrBlock: false
    cidrBlock: 192.168.0.0/16
    defaultNetworkAclId: acl-06a45ee85dc849f0e
    defaultRouteTableId: rtb-06c67bc60754fb583
    defaultSecurityGroupId: sg-0f461b7c9569aaad1
    dhcpOptionsId: dopt-037cbc88bae6bb04c
    enableDnsHostnames: true
    enableDnsSupport: true
    enableNetworkAddressUsageMetrics: false
    id: vpc-0fc5d6edf6d0769f2
    instanceTenancy: default
    ipv6AssociationId: ""
    ipv6CidrBlock: ""
    ipv6CidrBlockNetworkBorderGroup: ""
    ipv6IpamPoolId: ""
    ipv6NetmaskLength: 0
    mainRouteTableId: rtb-06c67bc60754fb583
    ownerId: "609897127049"
    region: us-west-2
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-93e2e6ed5c73
      crossplane-providerconfig: default
    tagsAll:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.m.upbound.io
      crossplane-name: configuration-aws-network-93e2e6ed5c73
      crossplane-providerconfig: default
  conditions:
  - lastTransitionTime: "2026-03-23T13:49:41Z"
    observedGeneration: 3
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2026-03-23T13:44:01Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-03-23T13:43:54Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
